# Generated by Django 5.0.4 on 2024-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=10)),
                ('courseDescription', models.TextField()),
                ('units', models.IntegerField()),
            ],
        ),
    ]
