# Generated by Django 5.0.4 on 2024-06-03 09:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=courses.models.submission_upload_to),
        ),
    ]
