# Generated by Django 5.0.4 on 2024-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_submission_comment'),
        ('users', '0020_remove_student_submitted_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_assignments', to='users.student'),
        ),
    ]
