# Generated by Django 5.0.4 on 2024-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_student'),
        ('users', '0020_remove_student_submitted_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.student'),
        ),
    ]
