# Generated by Django 5.0.4 on 2024-05-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_professor'),
        ('users', '0002_remove_student_coursesenrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursesEnrolled',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
