# Generated by Django 5.0.4 on 2024-05-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_professor'),
        ('users', '0003_alter_student_coursesenrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursesEnrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
