# Generated by Django 5.0.4 on 2024-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_professor'),
        ('users', '0004_alter_student_coursesenrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coursesEnrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='coursesEnrolled',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
