# Generated by Django 5.0.4 on 2024-05-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_program'),
        ('users', '0005_remove_student_coursesenrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.program'),
        ),
    ]
