# Generated by Django 5.0.4 on 2024-05-14 09:50

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_student_program'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
