# Generated by Django 5.0.4 on 2024-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('1', 'Instructor'), ('2', 'Student')], default='1', max_length=1),
        ),
    ]
