# Generated by Django 5.0.4 on 2024-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_program'),
        ('users', '0014_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursesEnrolled',
            field=models.ManyToManyField(related_name='enrolled_students', to='courses.course'),
        ),
    ]
