# Generated by Django 5.0.4 on 2024-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_assignment'),
        ('users', '0016_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submitted_assignments',
            field=models.ManyToManyField(related_name='submitted_by', to='courses.assignment'),
        ),
    ]
