# Generated by Django 5.0.4 on 2024-06-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_submitted_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('1', 'Instructor'), ('2', 'Student'), ('3', 'Admin')], default='1', max_length=1),
        ),
    ]
