# Generated by Django 5.0.4 on 2024-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('1', 'Instructor'), ('2', 'Student')], default='1', max_length=1),
        ),
    ]
