# Generated by Django 5.0.4 on 2024-06-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='submitted_assignments',
        ),
    ]
